# Generated by Django 4.2.16 on 2025-01-17 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='partList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('store', models.CharField(blank=True, max_length=8)),
                ('category', models.CharField(blank=True, max_length=16)),
                ('sub_cate', models.CharField(blank=True, max_length=128)),
                ('description', models.CharField(blank=True, max_length=256)),
                ('brand', models.CharField(blank=True, max_length=32)),
                ('spec1', models.CharField(blank=True, max_length=32)),
                ('unit1', models.CharField(blank=True, max_length=8)),
                ('spec2', models.CharField(blank=True, max_length=32)),
                ('unit2', models.CharField(blank=True, max_length=8)),
                ('spec3', models.CharField(blank=True, max_length=32)),
                ('unit3', models.CharField(blank=True, max_length=8)),
                ('spec4', models.CharField(blank=True, max_length=32)),
                ('unit4', models.CharField(blank=True, max_length=8)),
                ('orgPrice', models.IntegerField(blank=True, null=True)),
                ('saleEnd', models.DateField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
