# Generated by Django 4.2.16 on 2025-02-13 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataCollect', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='autoupdateLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField()),
                ('updateResult', models.CharField(max_length=8)),
            ],
        ),
    ]
