# Generated by Django 4.2.16 on 2025-02-13 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataCollect', '0002_autoupdatelog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autoupdatelog',
            name='datetime',
        ),
        migrations.AddField(
            model_name='autoupdatelog',
            name='coolpcUpdate',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='autoupdatelog',
            name='dataClean',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='autoupdatelog',
            name='dataParse',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='autoupdatelog',
            name='newtonUpdate',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='autoupdatelog',
            name='weekDay',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='autoupdatelog',
            name='updateResult',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='autoupdatelog',
            name='dateTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
